In [1]:
!pip install jax

  Using cached jax-0.7.2-py3-none-any.whl.metadata (13 kB)
  Using cached jaxlib-0.7.2-cp313-cp313-manylinux_2_27_x86_64.whl.metadata (1.3 kB)
  Using cached ml_dtypes-0.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.9 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached scipy-1.16.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (62 kB)
Using cached jax-0.7.2-py3-none-any.whl (2.8 MB)
Using cached jaxlib-0.7.2-cp313-cp313-manylinux_2_27_x86_64.whl (78.2 MB)
Using cached ml_dtypes-0.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (4.9 MB)
Using cached scipy-1.16.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (35.7 MB)
Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [jax]━━━━━━━ 4/5 [jax]ib]


In [2]:
import jax.numpy as jnp

jax arrays are just like numpy arrays but they are immutable

In [3]:
a = jnp.array([1, 2, 3])
b = jnp.array([2, 4, 6])

In [4]:
a + b

Array([3, 6, 9], dtype=int32)

In [5]:
a - b

Array([-1, -2, -3], dtype=int32)

In [6]:
a * b

Array([ 2,  8, 18], dtype=int32)

In [7]:
a / b

Array([0.5, 0.5, 0.5], dtype=float32)

In [8]:
a ** 2

Array([1, 4, 9], dtype=int32)