In [96]:
!pip install numpy

In [97]:
import numpy as np

In [98]:
#to get the version of the numpy
print(np.__version__)

2.3.3


numpy arrays = a very efficient multi dimensional array

In [99]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 4, 6])

In [100]:
arr1

array([1, 2, 3])

In [101]:
type(arr1)

numpy.ndarray

to get the shape of the array

In [102]:
arr1.shape

(3,)

to get the data type of elements in the numpy array

In [103]:
arr1.dtype

dtype('int64')

to get the dimensions of the array

In [104]:
arr1.ndim

1

to get the total number of elements

In [105]:
arr1.size

3

to get number of bytes required to store a element of the array

In [106]:
arr1.itemsize

8

element access works just like python lists

In [107]:
arr1[0]

np.int64(1)

numpy arrays are mutable

In [108]:
arr1[0] += 1

Doing arithmetic ops on two numpy array does element wise arithmetic op on the individual elements

In [109]:
arr1 + arr2

array([4, 6, 9])

In [110]:
arr1 - arr2

array([ 0, -2, -3])

In [111]:
arr1 * arr2

array([ 4,  8, 18])

In [112]:
arr1 / arr2

array([1. , 0.5, 0.5])

In [113]:
arr1 ** 2

array([4, 4, 9])

element wise application of square root on a numpy array

In [114]:
np.sqrt(arr1)

array([1.41421356, 1.41421356, 1.73205081])

element wise application of log on a numpy array

In [115]:
np.log(arr1)

array([0.69314718, 0.69314718, 1.09861229])

Dot Product

In [116]:
np.dot(arr1, arr2)

np.int64(30)

Sum of all the elements of the array

In [117]:
np.sum(arr1)

np.int64(7)

Another way to calculate the dot product

In [118]:
arr1 @ arr2

np.int64(30)

multi dimensional arrays

In [119]:
m_arr = np.array([[1, 2], [2, 4]])

In [120]:
m_arr

array([[1, 2],
       [2, 4]])

In [121]:
m_arr.shape # gives out (number of rows, number of columns)

(2, 2)

In [122]:
m_arr.ndim

2

In [123]:
m_arr_1 = np.array([[1, 2, 3], [2, 4, 6]])

In [124]:
m_arr_1.shape

(2, 3)

In [125]:
m_arr_1.ndim

2

In [126]:
m_arr[0]

array([1, 2])

In [127]:
m_arr[0][0]

np.int64(1)

another way to do the above thing

In [128]:
m_arr[0, 0]

np.int64(1)

In [129]:
m_arr[1] += 1

In [130]:
m_arr

array([[1, 2],
       [3, 5]])

to get the first column

In [131]:
m_arr[:,0]

array([1, 3])

to get the first row

In [132]:
m_arr[0, :]

array([1, 2])

to transpose the matrix (multi dimensional numpy array)

In [133]:
m_arr.T

array([[1, 3],
       [2, 5]])

to get the inverse of the matrix ( inverses can only be calculated for square matrices )

In [134]:
np.linalg.inv(m_arr)

array([[-5.,  2.],
       [ 3., -1.]])

to get the determinant of the matrix ( determinant can only be calculated for square matrices )

In [135]:
np.linalg.det(m_arr)

np.float64(-1.0000000000000004)

to get the diagonal of the matrix

In [136]:
d = np.linalg.diagonal(m_arr)

In [137]:
np.diag(d)

array([[1, 0],
       [0, 5]])

Slicing of numpy arrays is as similar as python lists

In [138]:
m_arr[0][1] # row = 0, column  = 1

np.int64(2)

In [139]:
m_arr[0, 1]

np.int64(2)

In [140]:
m_arr_1

array([[1, 2, 3],
       [2, 4, 6]])

In [141]:
m_arr_1[0,:2] # row = 0 until column 2 ( 2 not included )

array([1, 2])

In [142]:
m_arr_1[:,0]

array([1, 2])

In [143]:
m_arr_2 = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])

In [144]:
m_arr_2

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [145]:
m_arr_2[:2, 0] # rows = 0 to 2 and 0 th column

array([1, 2])

In [146]:
m_arr_2[1:3, 0]

array([2, 3])

In [147]:
m_arr_2[1:3, 1]

array([4, 6])

In [148]:
m_arr_2[:2, 1:] # first two of columns after 1 (including 1)

array([[2, 3],
       [4, 6]])

negitive indexing also works in numpy arrays 

In [149]:
m_arr_2[-1]

array([3, 6, 9])

apply a condition to all elements of the numpy array

In [150]:
m_arr_2 > 3

array([[False, False, False],
       [False,  True,  True],
       [False,  True,  True]])

to get the elements where some condition is true

In [151]:
m_arr_2[m_arr_2 > 3]

array([4, 6, 6, 9])

apply the condition and get the elements where its true and still retain the structure of the array by replacing the elements where the condition evaluated to false with something else

In [152]:
np.where(m_arr_2 > 3, m_arr_2, -1)

array([[-1, -1, -1],
       [-1,  4,  6],
       [-1,  6,  9]])

To access elements at multiple indices at once

In [153]:
arr3 = np.array([i*i for i in range(10)])
arr3[[1, 3, 5]]

array([ 1,  9, 25])

To get the arguments of elements where some condition is true

In [154]:
np.argwhere(arr3 % 2 == 0)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [155]:
idx = np.argwhere(arr3 % 2 == 0).flatten()

To access the elements based on above computation

In [156]:
arr3[idx]

array([ 0,  4, 16, 36, 64])

To create a numpy arrays filled with values between a range

In [157]:
arr4 = np.arange(1, 10)
print(arr4)

[1 2 3 4 5 6 7 8 9]


In [158]:
arr4.shape

(9,)

To change the shape of the array

In [159]:
arr4.reshape((3, 3)) # not in-place

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [160]:
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

To add a new axis to the data

In [161]:
arr5 = arr4[np.newaxis, :]

In [162]:
arr5.shape

(1, 9)

In [163]:
arr5.ndim

2

To concatenate two numpy arrays

In [164]:
np.concat((arr1, arr2))

array([2, 2, 3, 2, 4, 6])

In [165]:
np.concatenate((arr1, arr2.T), axis=0)

array([2, 2, 3, 2, 4, 6])

In [166]:
arr6 = np.array([1, 2, 3, 4])
arr7 = np.array([5, 6, 7, 8])

Horizontal Stack

In [167]:
m_arr_3 = np.hstack((arr6, arr7))
print(m_arr_3)

[1 2 3 4 5 6 7 8]


Vertical Stack

In [168]:
m_arr_4 = np.vstack((arr6, arr7))
print(m_arr_4)

[[1 2 3 4]
 [5 6 7 8]]


Broadcasting

In [169]:
arr8 = np.array([1, 2, 3])
arr9 = np.array([3])

In [170]:
arr8 + arr9 # internally arr9 is "broadcasted to [3, 3, 3]"

array([4, 5, 6])

To get the sum of all the elements in the array

In [171]:
arr8.sum()

np.int64(6)

In [172]:
m_arr_2[2] += 1
print(m_arr_2)

[[ 1  2  3]
 [ 2  4  6]
 [ 4  7 10]]


In [173]:
m_arr_2.sum(axis=0) # along the rows

array([ 7, 13, 19])

In [174]:
m_arr_2.sum(axis = 1) # along the columns

array([ 6, 12, 21])

similarly to calculate the mean

In [175]:
m_arr_2.mean(axis=0)

array([2.33333333, 4.33333333, 6.33333333])

In [176]:
m_arr_2.mean(axis=1)

array([2., 4., 7.])

variance

In [177]:
m_arr_2.var(axis=0)

array([1.55555556, 4.22222222, 8.22222222])

In [178]:
m_arr_2.var(axis=1)

array([0.66666667, 2.66666667, 6.        ])

Standard Deviation

In [179]:
m_arr_2.std(axis=0)

array([1.24721913, 2.05480467, 2.86744176])

In [180]:
m_arr_2.std(axis=1)

array([0.81649658, 1.63299316, 2.44948974])

to get min element of the array

In [181]:
m_arr_2.min()

np.int64(1)

to get the max element of the array

In [182]:
m_arr_2.max()

np.int64(10)

In [183]:
arr9 = np.array([1.0, 2.0, 3.0])
print(arr9.dtype) # default float type

float64


to set the dtype of an numpy array during its creation

In [184]:
arr9 = np.array([1.0, 2.0, 3.0], dtype=np.float32)

In [185]:
arr9 = np.array([1.0,2.0,3.0], dtype=np.float16)

the below thing does not do deep copy so change in one gets reflected in another

In [186]:
arr10 = arr9

In [187]:
print(arr10)
print(arr9)

[1. 2. 3.]
[1. 2. 3.]


In [188]:
arr10[0] += 1

In [189]:
print(arr10)
print(arr9)

[2. 2. 3.]
[2. 2. 3.]


Some ways to generate basic arrays

In [192]:
arr9 = np.zeros((3, 3))
print(arr9)
print(arr9.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


In [193]:
arr9 = np.ones((3, 3))
print(arr9)
print(arr9.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64


array of shape (3, 3) filled with 5.0

In [195]:
arr9 = np.full((3, 3), 5.0)
print(arr9)
print(arr9.dtype)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
float64


to create a identity matrix

In [196]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [197]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [198]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

create a array with 20 elements such that all the elements are in between 10 and 20 and are evenly spaced

In [199]:
np.linspace(10, 20, 20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

To generate arrays filled with random numbers

random numbers from uniform distribution

In [203]:
np.random.random((3, 3))

array([[0.78369887, 0.13477445, 0.11989914],
       [0.95654989, 0.31464353, 0.20179697],
       [0.05687666, 0.65844691, 0.95008726]])

random numbers from the gaussian distribution

In [207]:
arr9 = np.random.randn(3, 3)
print(arr9)
print(arr9.mean())
print(arr9.var())

[[-0.06672539  0.48354307  0.68726178]
 [-1.74098654  0.14844576 -0.43839091]
 [ 0.28776099  0.33032008 -2.89255515]]
-0.3557029220491008
1.2639915193121


random integers

In [ ]:
np.random.randint(1, 10, (3,3)) #start, stop, shape

array([[8, 4, 4],
       [5, 2, 1],
       [8, 1, 1]])

randomly pick elements from a list of values

In [210]:
np.random.choice([i for i in range(5)], (3, 3))

array([[2, 0, 2],
       [0, 4, 1],
       [1, 1, 3]])

Linear Algebra

to get eigen values and eigen vectors

In [211]:
mt = np.array([[1, 2], [3, 4]])


In [ ]:
eigen_values, eigen_vectors = np.linalg.eig(mt)
print(eigen_values)
print(eigen_vectors) # column vectors

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


eigen_value * eigen_vector = matrix * eigen vector

In [214]:
print(eigen_vectors[:,0] * eigen_values[0])
print(mt @ eigen_vectors[:, 0])

[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]


In [215]:
i1 = eigen_vectors[:,0] * eigen_values[0]
i2 = mt @ eigen_vectors[:, 0]

to compare two floating point values

In [216]:
np.allclose(i1, i2)

True

Solving Linear System

In [217]:
A = np.array([[1.0, 1.0], [1.5, 4]])
b = np.array([2200, 5050])

Ax = b

x = inv(A) * b

In [220]:
x = np.linalg.inv(A).dot(b)

In [221]:
x

array([1500.,  700.])

another way

In [222]:
np.linalg.solve(A, b)

array([1500.,  700.])

To load a csv file using numpy

In [223]:
data = np.loadtxt('trial2.csv', delimiter=",", dtype=np.float16)

In [224]:
data

array([[1., 2., 3.],
       [2., 4., 6.],
       [3., 6., 9.]], dtype=float16)

In [225]:
data.shape

(3, 3)

another way

In [226]:
data = np.genfromtxt('trial2.csv', delimiter=",", dtype=np.float16)

In [227]:
data

array([[1., 2., 3.],
       [2., 4., 6.],
       [3., 6., 9.]], dtype=float16)

In [228]:
data.shape

(3, 3)